### ISSUE TITLE
What is that?

### ISSUE THREAD

**Issue by AngeloMetal** [PawelGorny/LifeClassic#1]
I'm trying to understand it by reading the wikipedia link, but I still don't get it. What is the game of life exactly and, if it's a real game, how is it played?

**Comment by PawelGorny** [comment]
It is a game - kind of emulation emulation. You specify the initial state, the state for the next round is calculated base on some rules (https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life#Rules)
The point is to have the longest possible life of your civilization. Or create a stable state. https://www.youtube.com/watch?v=R9Plq-D1gEk
BTW: this version was prepared for compilation using cordova (as a mobile app), so it probably will not work in the normal browser (at least not out of the box...).

**Comment by AngeloMetal** [comment]
It doesn't seem to work on me. I download the files and open ``index.html`` with browser right?

**Comment by PawelGorny** [comment]
Yes, but as I said, it will not work as long as you do not compile it and launch on mobile (it was built for BlackBerry 10).
But wait, I will add a simple file prepared for browser.

**Comment by PawelGorny** [comment]
Try to open file indexBrowser.html - now you should see 'start' button. There is still warning when game ends, but I am not going to fix it now.

**Comment by AngeloMetal** [comment]
Okay, thanks, it works.
